name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: welcome message
        run: echo "Welcome to my first workflow!"

      - name: list files
        run: ls -la

      - name: Read file
        run: cat README.md
