name: Generate ASCII Artwork
# This workflow generates ASCII artwork using the cowsay action and saves it to a file.

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cowsay
        uses: sudo apt-get install cowsay -y

      - name: Execute cowsay cmd
        uses: cowsay -f dragon "Run for cover, I am a DRAGON!" >> dragon.txt


      -  name: Test file exists
         uses: grep -i "dragon" dragon.txt

      -  name: Read file
         run: cat dragon.txt
        
      - name: checkout repo files
        uses: ls -ltra

    