name: Matrix Configuration

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: alpine
    runs-on: ${{ matrix.os }}
    steps:
      - name: Docker info
        run: docker info

      - name: Run Docker image
        run: docker run ${{ matrix.images }}
